config/urls.py
# config/urls.py

from django.contrib import admin
from django.urls import path, include

app_name="portfolio"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
]

portfolio/urls.py
from . import views
from django.urls import path

app_name = "portfolio"

urlpatterns = [
    path('', views.home_page_view, name='home'),
    path('home', views.home_page_view, name='home'),
    path('projetos', views.projetos_page_view, name='projetos'),
    path('licenciatura', views.licenciatura_page_view, name='licenciatura'),
    path('blog', views.blog_page_view, name='blog'),
    path('web/', views.web_page_view, name='web'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('weather', views.weather_page_view, name='weather'),
    path('novo_post', views.novo_post_page_view, name='novo_post'),
    path('edita_post/<int:post_id>', views.edita_post_page_view, name='edita_post'),
    path('apaga_post/<int:post_id>', views.apaga_post_page_view, name='apaga_post'),
    path('nova_cadeira', views.nova_cadeira_page_view, name='nova_cadeira'),
    path('edita_cadeira/<int:cadeira_id>', views.edita_cadeira_page_view, name='edita_cadeira'),
    path('apaga_cadeira/<int:cadeira_id>', views.apaga_cadeira_page_view, name='apaga_cadeira'),
    path('novo_projeto', views.novo_projeto_page_view, name='novo_projeto'),

    path('edita_projeto/<int:projeto_id>', views.edita_projeto_page_view, name='edita_projeto'),
    path('apaga_projeto/<int:projeto_id>', views.apaga_projeto_page_view, name='apaga_projeto'),
    path('novo_professor', views.novo_professor_page_view, name='novo_professor'),
]

portfolio/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    autor = models.CharField(max_length=30)
    data = models.DateTimeField(auto_now_add=True)
    titulo = models.CharField(max_length=30)
    descricao = models.TextField(max_length=255)

    def __str__(self):
        return f'"{self.titulo}" por {self.autor}'


class Professor(models.Model):
    nome = models.CharField(max_length= 64)
    imagem = models.ImageField(upload_to='pictures/', null=True, blank=True)

    def __str__(self):
        return self.nome


class Cadeira(models.Model):
    nome = models.CharField(max_length=64)
    ects = models.IntegerField(default=1)
    ano = models.IntegerField(default=1)
    semestre = models.IntegerField(default=1)
    topicos = models.CharField(max_length=255)
    ranking = models.IntegerField(default=1)
    imagem = models.ImageField(upload_to='pictures/', blank=True)
    professor = models.ForeignKey(Professor, on_delete=models.PROTECT, related_name="Cadeiras")

    def __str__(self):
        return self.nome


class Projeto(models.Model):
    titulo = models.CharField(max_length=30)
    descricao = models.CharField(max_length=255)
    imagem = models.ImageField(upload_to='pictures/', null=True, blank=True)
    cadeira = models.ForeignKey(Cadeira, on_delete=models.PROTECT, related_name="Projetos")

    def __str__(self):
        return self.titulo


class PontuacaoQuizz(models.Model):
    nome = models.CharField(max_length=30)
    pontuacao = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.nome} : {self.pontuacao} pontos'

portfolio/forms.py
from django import forms
from django.forms import ModelForm
from .models import Post
from .models import Cadeira
from .models import Projeto
from .models import Professor


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

        widgets = {
            'autor': forms.TextInput(attrs={'class': 'inputText'}),
            'titulo': forms.TextInput(attrs={'class': 'inputText'}),
            'descricao': forms.Textarea(attrs={'class': 'inputText'}),
        }


class CadeiraForm(ModelForm):
    class Meta:
        model = Cadeira
        fields = '__all__'

        widgets = {
            'nome': forms.TextInput(attrs={'class': 'inputText'}),
            'ects': forms.RadioSelect(choices=[(5, 5), (6, 6), (20, 20)], attrs={'class': 'inputRadio'}),
            'ano': forms.RadioSelect(choices=[(1, "1º"), (2, "2º"), (3, "3º")], attrs={'class': 'inputRadio'}),
            'semestre': forms.RadioSelect(choices=[(1, "1º"), (2, "2º")], attrs={'class': 'inputRadio'}),
            'topicos': forms.Textarea(attrs={'class': 'inputText'}),
            'ranking': forms.RadioSelect(choices=[(1, "⭐"), (2, "⭐⭐"), (3, "⭐⭐⭐"), (4, "⭐⭐⭐⭐"), (5, "⭐⭐⭐⭐⭐")], attrs={'class': 'inputRadio'}),
        }


class ProjetoForm(ModelForm):
    class Meta:
        model = Projeto
        fields = '__all__'

        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'inputText'}),
            'descricao': forms.Textarea(attrs={'class': 'inputText'}),
        }


class ProfessorForm(ModelForm):
    class Meta:
        model = Professor
        fields = '__all__'

        widgets = {
            'nome': forms.TextInput(attrs={'class': 'inputText'}),
        }

portfolio/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from .forms import PostForm
from .forms import CadeiraForm
from .forms import ProjetoForm
from .forms import ProfessorForm
from .models import Post
from .models import Cadeira
from .models import Projeto
from .models import Professor
from .models import PontuacaoQuizz

from matplotlib import pyplot as plt
import io
import urllib
import base64
import matplotlib

matplotlib.use('Agg')
# Create your views here.


def home_page_view(request):
        return render(request, 'portfolio/home.html')


def projetos_page_view(request):
    context = {'projetos': Projeto.objects.all()}
    return render(request, 'portfolio/projetos.html', context)


def licenciatura_page_view(request):
    context = {'cadeiras': Cadeira.objects.all()}
    return render(request, 'portfolio/licenciatura.html', context)


def blog_page_view(request):
    context = {'posts': Post.objects.all()}

    return render(request, 'portfolio/blog.html', context)


def pontuacao_quizz(request):
    score = 0
    if request.POST['questao1'] == 'b':
        score += 1

    if request.POST['questao2'] == 'b':
        score += 1

    if request.POST['questao3'] == 'a':
        score += 1

    return score


def web_page_view(request):
    if request.method == 'POST':
        n = request.POST['nome']
        p = pontuacao_quizz(request)
        r = PontuacaoQuizz(nome=n, pontuacao=p)
        r.save()

    context = {
        'data': desenha_grafico_resultados()
    }

    return render(request, 'portfolio/web.html', context)


def desenha_grafico_resultados():
        pontuacoes = PontuacaoQuizz.objects.all().order_by('pontuacao')

        nomesList = [pontuacao.nome for pontuacao in pontuacoes]
        pontuacaoList = [pontuacao.pontuacao for pontuacao in pontuacoes]

        plt.barh(nomesList, pontuacaoList)
        plt.ylabel("Pontuacao")
        plt.autoscale()

        fig = plt.gcf()
        plt.close()

        buf = io.BytesIO()
        fig.savefig(buf, format='png')

        buf.seek(0)
        string = base64.b64encode(buf.read())
        uri = urllib.parse.quote(string)

        return uri


def login_view(request):

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(
            request,
            username=username,
            password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('portfolio:home'))
        else:
            return render(request, 'portfolio/login.html', {
                'message': 'Credenciais invalidas.'
            })

    return render(request, 'portfolio/login.html')


def logout_view(request):
    logout(request)

    return render(request, 'portfolio/login.html', {
        'message': 'Foi desconetado.'
    })


def weather_page_view(request):
    return render(request, 'portfolio/weather.html')


def novo_post_page_view(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:blog'))

    context = {'form': form}

    return render(request, 'portfolio/novo_post.html', context)


def edita_post_page_view(request, post_id):
    post = Post.objects.get(pk=post_id)
    form = PostForm(request.POST or None, instance=post)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:blog'))

    context = {'form': form, 'post_id': post_id}

    return render(request, 'portfolio/edita_post.html', context)


def apaga_post_page_view(request, post_id):
    Post.objects.get(id=post_id).delete()
    return HttpResponseRedirect(reverse('portfolio:blog'))


@login_required
def nova_cadeira_page_view(request):
    form = CadeiraForm(request.POST, request.FILES or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:licenciatura'))

    context = {'form': form}

    return render(request, 'portfolio/nova_cadeira.html', context)


@login_required
def edita_cadeira_page_view(request, cadeira_id):
    cadeira = Cadeira.objects.get(pk=cadeira_id)
    form = CadeiraForm(request.POST or None, instance=cadeira)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:licenciatura'))

    context = {'form': form, 'cadeira_id': cadeira_id}

    return render(request, 'portfolio/edita_cadeira.html', context)


@login_required
def apaga_cadeira_page_view(request, cadeira_id):
    Cadeira.objects.get(id=cadeira_id).delete()
    return HttpResponseRedirect(reverse('portfolio:licenciatura'))


@login_required
def novo_projeto_page_view(request):
    form = ProjetoForm(request.POST, request.FILES or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:projetos'))

    context = {'form': form}

    return render(request, 'portfolio/novo_projeto.html', context)


@login_required
def edita_projeto_page_view(request, projeto_id):
    projeto = Projeto.objects.get(pk=projeto_id)
    form = ProjetoForm(request.POST or None, instance=projeto)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:projetos'))

    context = {'form': form, 'projeto_id': projeto_id}

    return render(request, 'portfolio/edita_projeto.html', context)


@login_required
def apaga_projeto_page_view(request, projeto_id):
    Projeto.objects.get(id=projeto_id).delete()
    return HttpResponseRedirect(reverse('portfolio:projetos'))

@login_required
def novo_professor_page_view(request):
    form = ProfessorForm(request.POST, request.FILES or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:home'))

    context = {'form': form}

    return render(request, 'portfolio/novo_professor.html', context)

portfolio/templates/portfolio/blog.html
{% extends 'portfolio/layout.html' %}

{% block main %}
{% load static %}
<link rel="stylesheet" href="{% static 'portfolio/css/blog.css' %}">
    <section>
        <h3>Blog</h3>
        <a href="{% url 'portfolio:novo_post' %}" class="new_post">Novo Post</a>
        <div class="posts_container">
            {% for post in posts %}
                <div class="post">
                    <div class="post-inicial">
                        <div>
                            <h2>{{ post.titulo }}</h2>
                            <p>{{ post.autor }}</p>
                            <a href="{% url 'portfolio:edita_post' post.id %}" class="botao_editar">
                               <button>
                                    <i class="material-icons" style="color:black">edit</i>
                               </button>
                            </a>
                        </div>
                    </div>
                    <div class="post-overlay"></div>
                    <div class="post-content">
                        <h2>{{ post.titulo }}</h2>
                        <p>{{ post.descricao }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>

    </section>


{% endblock %}

portfolio/templates/portfolio/edita_cadeira.html
{% extends 'portfolio/layout.html' %}

{% block main %}
{% load static %}
<link rel="stylesheet" href="{% static 'portfolio/css/edita.css' %}">
    <section>
        <h3>Editar</h3>
        <div class="edita">
            <form action="{% url 'portfolio:edita_cadeira' cadeira_id %}" method="POST" autocomplete="off" enctype="multipart/form-data">
                {% csrf_token %}

                {{form.as_p}}

                <div class="buttons">
                    <a href="{% url 'portfolio:licenciatura' %}" role="button" class="btn">Cancelar</a>
                    <input type="submit" value="Gravar" class="btn" >
                    <a href="{% url 'portfolio:apaga_cadeira' cadeira_id %}" role="button" class="btn">Apagar</a>
                </div>

            </form>
        </div>
    </section>
{% endblock %}

portfolio/templates/portfolio/edita_post.html
{% extends 'portfolio/layout.html' %}

{% block main %}
{% load static %}
<link rel="stylesheet" href="{% static 'portfolio/css/edita.css' %}">
    <section>
        <h3>Editar</h3>
        <div class="edita">
            <form action="{% url 'portfolio:edita_post' post_id %}" method="POST" autocomplete="off">
                {% csrf_token %}

                {{form.as_p}}

                <div class="buttons">
                    <a href="{% url 'portfolio:blog' %}" role="button" class="btn">Cancelar</a>
                    <input type="submit" value="Gravar" class="btn" >
                    <a href="{% url 'portfolio:apaga_post' post_id %}" role="button" class="btn">Apagar</a>
                </div>

            </form>
        </div>
    </section>
{% endblock %}

portfolio/templates/portfolio/edita_projeto.html
{% extends 'portfolio/layout.html' %}

{% block main %}
{% load static %}
<link rel="stylesheet" href="{% static 'portfolio/css/edita.css' %}">
    <section>
        <h3>Editar</h3>
        <div class="edita">
            <form action="{% url 'portfolio:edita_projeto' projeto_id %}" method="POST" autocomplete="off"  enctype="multipart/form-data">
                {% csrf_token %}

                {{form.as_p}}

                <div class="buttons">
                    <a href="{% url 'portfolio:projetos' %}" role="button" class="btn">Cancelar</a>
                    <input type="submit" value="Gravar" class="btn" >
                    <a href="{% url 'portfolio:apaga_projeto' projeto_id %}" role="button" class="btn">Apagar</a>
                </div>

            </form>
        </div>
    </section>
{% endblock %}

portfolio/templates/portfolio/home.html
{% extends 'portfolio/layout.html' %}

{% block main %}
{% load static %}
<link rel="stylesheet" href="{% static 'portfolio/css/home.css' %}">

    <section class="hero-image">
        {% load static %}
        <video src="{% static 'portfolio/images/HeroImage.mp4' %}" muted loop autoplay></video>
        <div class="overlay"></div>
        <div class="text-hero-image">
            <h2>O meu portfolio</h2>
            <p>Olá sou o Diogo e sou estudande de engenharia informatica</p>
            <a href="#sobre">Sobre Mim</a>
        </div>
    </section>
    <section class="sobre" id="sobre">
        <div>
            {% load static %}
            <img src="{% static 'portfolio/images/eu.jpg' %}">
            <h3>Diogo Cerqueira</h3>
            <p>Olá! Tenho 20 anos e terminei o ensino médio
            em economia e candidatei-me a uma licenciatura em
            engenharia informática para seguir o que
            pretendo fazer o que é Software Developer</p>
        </div>
    </section>



{% endblock %}

portfolio/templates/portfolio/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="pt">
<head>
    <title>Portfolio</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    {% load static %}
    <link rel="stylesheet" href="{% static 'portfolio/css/layout.css' %}">
    <script src="{% static 'portfolio/js/weather.js' %}"></script>
    <script src="{% static 'portfolio/js/clock.js' %}"></script>

</head>
<body>
    <header>
        <nav>
            <a class="nome" href="">Diogo Cerqueira</a>
            <div class="container">
                <div>
                    <h1 class="temp"></h1>
                    <div class="city-time">
                        <h1 class="name"></h1>
                        <small>
                            <span class="time" id = "clock"></span>

                            <span class="date">
                            </span>
                        </small>
                    </div>
                    <div class="weather">
                        <img src="" alt="icon" class="icon" height="50" width="50">
                        <small>
                            <span class="condition"></span>
                        </small>
                    </div>
                </div>
            </div>


            <div class="mobile-menu">
                <div class="line1"></div>
                <div class="line2"></div>
                <div class="line3"></div>
            </div>
            <ul class="nav-list">
                <li><a href="{% url 'portfolio:home' %}">Home</a></li>
                <li><a href="{% url 'portfolio:licenciatura' %}">Licenciatura</a></li>
                <li><a href="{% url 'portfolio:projetos' %}">Projetos</a></li>
                <li><a href="{% url 'portfolio:blog' %}">Blog</a></li>
                <li><a href="{% url 'portfolio:web' %}">Web</a></li>
                <li>
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'portfolio:logout' %}">Logout</a>
                    {% else %}
                        <a href="{% url 'portfolio:login' %}">Login</a>
                    {% endif %}
                </li>
            </ul>
      </nav>
    </header>
    <main>
        {% block main %}

        {% endblock main %}
    </main>
    <footer>
        ULHT, 2022
    </footer>

    <script src="{% static 'portfolio/js/mobile-navbar.js' %}"></script>
</body>
</html>

portfolio/templates/portfolio/licenciatura.html
{% extends 'portfolio/layout.html' %}

{% block main %}
{% load static %}
<link rel="stylesheet" href="{% static 'portfolio/css/licenciatura.css' %}">

	<section>
        <h3>Licenciatura</h3>
        {% if request.user.is_authenticated %}
            <a href="{% url 'portfolio:nova_cadeira' %}" class="new_cadeira">Nova Cadeira</a>
            <a href="{% url 'portfolio:novo_professor' %}" class="new_professor">Novo Professor</a>
        {% endif %}

        <div class="cadeira_container">
            {% for cadeira in cadeiras %}
                <div class="cadeira">
                    <div class="cadeira-img">
                        {% load static %}
                        <img src="{{ cadeira.imagem.url }}">
                    </div>
                    <div class="cadeira-body">
                        {% if request.user.is_authenticated %}
                        <a href="{% url 'portfolio:edita_cadeira' cadeira.id %}" class="botao_editar">
                           <button>
                                <i class="material-icons" style="color:black">edit</i>
                           </button>
                        </a>
                        {% endif %}

                        <span class="cadeira-nome"> {{ cadeira.nome}} </span>
                        <span class="cadeira-ects">{{ cadeira.ects }} ECTS</span>
                        <h4>
                            {{ cadeira.topicos }}
                        </h4>
                        <p>
                            {{ cadeira.ano }} ano {{ cadeira.semestre }} semestre
                        </p>
                        <p>
                            {% if cadeira.ranking == 1 %}
                                ⭐
                            {% elif cadeira.ranking == 2 %}
                                ⭐⭐
                            {% elif cadeira.ranking == 3 %}
                                ⭐⭐⭐
                            {% elif cadeira.ranking == 4 %}
                                ⭐⭐⭐⭐
                            {% elif cadeira.ranking == 5 %}
                                ⭐⭐⭐⭐⭐
                            {% endif %}
                        </p>
                        <div class="cadeira-prof">
                            <img src="{{ cadeira.professor.imagem.url }}">
                            <div class="prof-info">
                                <h5>{{ cadeira.professor.nome }}</h5>
                            </div>
                        </div>
                    </div>

                </div>
            {% endfor %}
        </div>
    </section>
{% endblock %}

portfolio/templates/portfolio/login.html
{% extends "portfolio/layout.html" %}

{% block main %}
{% load static %}
<link rel="stylesheet" href="{% static 'portfolio/css/login.css' %}">
    <section>
        <h3>Login</h3>

        <div class="login">
            <form action="{% url 'portfolio:login' %}" method="POST" autocomplete="off">
                {% csrf_token %}

                {% if message %}
                    <p> {{ message }} </p>
                {% endif %}

                <div class="inputBox">
                    <input type="text" name="username" id="username" class="inputText" required>
                    <label for="username" class="labelInput">Username</label>
                </div>
                <br>
                <div class="inputBox">
                    <input type="password" name="password" id="password" class="inputText" required>
                    <label for="password" class="labelInput">Password</label>
                </div>
                <br>

                <input type="submit" id="submit" value="Login">
            </form>



        </div>
    </section>



{% endblock main %}

portfolio/templates/portfolio/nova_cadeira.html
{% extends 'portfolio/layout.html' %}

{% block main %}
{% load static %}
<link rel="stylesheet" href="{% static 'portfolio/css/novo2.css' %} ">
    <section>
        <h3>Nova Cadeira</h3>
        <div class="novo">
            <form method="post" action="" autocomplete="off" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" value="Gravar" id="submit">
            </form>
        </div>
    </section>
{% endblock %}

portfolio/templates/portfolio/novo_post.html
{% extends 'portfolio/layout.html' %}

{% block main %}
{% load static %}
<link rel="stylesheet" href="{% static 'portfolio/css/novo.css' %}">
    <section>
        <h3>Novo post</h3>
        <div class="novo">
            <form method="post" action="" autocomplete="off">
                {% csrf_token %}
                <p>
                    <input type="text" name="autor" class="inputText" maxlength="30" required="" id="id_autor">
                    <label for="id_autor">Autor:</label>
                </p>
                <br>
                <p>
                    <input type="text" name="titulo" class="inputText" maxlength="30" required="" id="id_titulo"><label for="id_titulo">Titulo:</label>
                    <label for="id_titulo">Titulo:</label>
                </p>
                <br>
                <p>
                    <textarea name="descricao" cols="40" rows="10" class="inputText" maxlength="255" required="" id="id_descricao"></textarea>
                    <label for="id_descricao">Descricao:</label>
                </p>
                <br>
                <br>
                <input type="submit" value="Gravar" id="submit">
            </form>
        </div>
    </section>
{% endblock %}

portfolio/templates/portfolio/novo_projeto.html
{% extends 'portfolio/layout.html' %}

{% block main %}
{% load static %}
<link rel="stylesheet" href="{% static 'portfolio/css/novo2.css' %}">
    <section>
        <h3>Novo Projeto</h3>
        <div class="novo">
            <form method="post" action="" autocomplete="off"  enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" value="Gravar" id="submit">
            </form>
        </div>
    </section>
{% endblock %}

portfolio/templates/portfolio/projetos.html
{% extends 'portfolio/layout.html' %}

{% block main %}
{% load static %}
<link rel="stylesheet" href="{% static 'portfolio/css/projetos.css' %}">

	<section>
        <h3>Projetos</h3>
        {% if request.user.is_authenticated %}
            <a href="{% url 'portfolio:novo_projeto' %}" class="new_projeto">Novo Projeto</a>
            <a href="{% url 'portfolio:novo_professor' %}" class="new_professor">Novo Professor</a>
        {% endif %}

        <div class="projeto_container">
            {% for projeto in projetos %}
                <div class="projeto">
                    <div class="projeto-img">
                        {% load static %}
                        <img src="{{ projeto.imagem.url }}">
                    </div>
                    <div class="projeto-body">
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'portfolio:edita_projeto' projeto.id %}" class="botao_editar">
                                <button>
                                    <i class="material-icons" style="color:black">edit</i>
                                </button>
                            </a>
                        {% endif %}

                        <span class="projeto-cadeira-nome"> {{ projeto.cadeira.nome }} </span>
                        <h4>
                            {{ projeto.titulo }}
                        </h4>
                        <p>
                            {{ projeto.descricao }}
                        </p>

                        <div class="projeto-prof">
                            <img src="{{ projeto.cadeira.professor.imagem.url }}">
                            <div class="prof-info">
                                <h5>{{ projeto.cadeira.professor.nome }}</h5>
                            </div>
                        </div>
                    </div>

                </div>
            {% endfor %}
        </div>
    </section>
{% endblock %}

portfolio/templates/portfolio/quizz.html
{% extends 'portfolio/layout.html' %}

{% block main %}
{% load static %}
<link rel="stylesheet" href="{% static 'portfolio/css/quizz.css' %}">
    <section>
        <div class="quizz">
            <form method="POST" action="" autocomplete="off" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset>
                <legend><b>Quizz</b></legend>
                <div class="inputBox">
                    <input type="text" name="nome" id="nome" class="inputNome" required>
                    <label for="nome" class="labelNome">Nome</label>
                </div>
                <br>

                <h1>Pergunta 1:</h1><br>
                <label>Qual o significado de HTML?</label><br><br>
                <input type="radio" id="1a" name="questao1" value="a">
                <label for="1a"> Home Tool Markup Language </label><br>
                <input type="radio" id="1b" name="questao1" value="b">
                <label for="1b"> Hyper Text Markup Language</label><br>
                <input type="radio" id="1c" name="questao1" value="c">
                <label for="1c"> Hyperlinks and Text Markup Language</label><br><br>

                <h1>Pergunta 2:</h1><br>
                <label>Qual dos seguintes atributos especifica um texto alternativo para uma imagem, se a imagem não puder ser exibida? </label><br><br>
                <input type="radio" id="2a" name="questao2" value="a">
                <label for="2a"> src </label><br>
                <input type="radio" id="2b" name="questao2" value="b">
                <label for="2b"> alt </label><br>
                <input type="radio" id="2c" name="questao2" value="c">
                <label for="2c"> title</label><br>
                <input type="radio" id="2d" name="questao2" value="d">
                <label for="2d"> legend </label><br><br>

                <h1>Pergunta 3:</h1><br>
                <label>Qual tipo de entrada define uma barra deslizante? </label><br><br>
                <input type="radio" id="3a" name="questao3" value="a">
                <label for="3a"> range </label><br>
                <input type="radio" id="3b" name="questao3" value="b">
                <label for="3b"> slider </label><br>
                <input type="radio" id="3c" name="questao3" value="c">
                <label for="3c"> search </label><br>
                <input type="radio" id="3d" name="questao3" value="d">
                <label for="3d"> controls </label>

                <br><br>
                <input type="submit" name="submit" id="submit">
            </fieldset>
        </form>
        </div>

        <img src="data:image/png;base64,{{ data }}" alt="graf">
    </section>
{% endblock %}